### ISSUE TITLE
Tags/keywords implementation

### ISSUE THREAD

**Issue by ilikerobots** [nuxt-company/demo-blog-nuxt-content#20]
I created a rough tag implementation, where tags are stored as content, similar to articles themselves.  Each has a name, description, and image. These are displayed on the front page and have dedicated routes to show articles tagged with the given tag.  Articles themselves are associated with tags via the frontmatter in the article content.

I'd be happy to clean this up and make a PR, but I'm not sure if you're accepting PRs, especially as the repo is linked to a tutorial article.

**Comment by debs-obrien** [comment]
Hey thanks for your hard work and suggestions. Sure make the pr and I can take a look at it. If it doesn't modify too much the main examples that shows in the article it might be ok or we might be able to add a piece to the article. hard to see until I see the code. But yeah go for it

**Comment by ilikerobots** [comment]
Ok, thanks for the reply.  I'll get back to you in a few days with a PR.
